name: Run SonarCloud with Maven

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'   # 'temurin' replaces 'adopt'
          cache: maven

      - name: Build and Analyze with SonarCloud
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=sonar-jenkins-project-githubactions \
          -Dsonar.organization=sonar-jenkins-demo-organization \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # automatically available
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # you must add this secret
