name: Run SonarQube with Maven

on:
push:
branches: [ master ]

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      java-version: '17'
      distribution: 'temurin'
      cache: maven

  - name: Build and analyze with SonarCloud
    run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
      -Dsonar.projectKey=sonar-jenkins-project-githubactions \
      -Dsonar.organization=sonar-jenkins-demo-organization \
      -Dsonar.host.url=https://sonarcloud.io \
      -Dsonar.token=${{ secrets.SONAR_TOKEN }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```
