name: SonarCloud - Maven Quality Analysis

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java (Temurin recommended by SonarCloud)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the Maven project
      - name: Build with Maven
        run: mvn -B clean verify

      # Step 4: Run SonarCloud analysis via Maven plugin
      - name: Run SonarCloud analysis
        run: |
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=sonar-jenkins-project-githubactions \
            -Dsonar.organization=sonar-jenkins-demo-organization \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # auto-created by GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # create this secret in your repo
